### ISSUE TITLE
Kawpow yiimp gone

### ISSUE THREAD

**Issue by sullystuff** [afiniel/Yiimp-install-Kudaraidee#1]
Hi, I couldn't find your contact info so decided to open an issue here in the hopes that you see it.
I cannot locate your kawpow fork anywhere on github - perhaps the visibility was changed? 
If you still have access, please reach out to me at   carter@sullynode.com  
If you do not have access or do not want to share it, I understand - but please still respond so I know to look elsewhere!

Thank you,
-Carter

**Comment by afiniel** [comment]
Hello! That was one old project, that yiimp that it clone from git is on my new project. https://github.com/afiniel/Yiimp-Pool-Installer, and the old kawpow fork was in another branch call "kawpow" if you have a look in install.sh and go to line 274 you see this:  hide_output git clone https://github.com/afiniel/yiimp.git -b kawpow-afiniel    the script hides the output and clone in to Branch kawpow. if you want to continue on this you can ofc fork it and find the kawpow branch from kudaraidee here https://github.com/Kudaraidee/yiimp/tree/kawpow

Good luck with the project!

Regards Afiniel

**Comment by sullystuff** [comment]
Thank you so much!

**Comment by nitrocon** [comment]
Hi! All kawpow related codes has been deleted, tell me if I am wrong.
Do you still have the cpp?

**Comment by afiniel** [comment]
I'm working on it i have a private repo  on git that i work on, that may be released soon. Regards

**Comment by afiniel** [comment]
Feel free to join our discord for updated, we have move to https://github.com/Afiniel-tech/ btw and discord you find in our Yiimpool installer page

**Comment by nitrocon** [comment]
Thanks for youre answer.
